#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2020 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_oniguruma::find_latest_version;

use strict;
use warnings;

use Cpanel::JSON::XS;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my $res    = $http->get("https://api.github.com/repos/kkos/oniguruma/releases/latest");
    my $latest = Cpanel::JSON::Load( $res->content );

    my $url     = $latest->{assets}[0]{browser_download_url};
    my $name    = $latest->{assets}[0]{name};
    my $version = $latest->{tag_name};                          # They do use some semi-unusual tags which could potentially confuse `et update`.
    $version =~ s/^v//;

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # github does not currently have a way to get the sum

    return;
}

__END__

=encoding utf-8

=head1 README

This is a Github project. The latest version is listed as a tag in the project.

They do use some semi-unusual tags which could potentially confuse `et update`.

